version: "3.8" # Specify the Docker Compose file version

services:
  db:
    image: postgres
    container_name: my-postgres-container
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./db/postgres-data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: my-backend-container
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"
